import {
  useState,
  useMemo,
  useEffect,
  useCallback,
  useRef,
  startTransition,
} from "react";
import { notify } from "../../../lib/notify";
import { normalizeCurrencyCode } from "../../../lib/format/formatCurrency";
import { compactYmd, localYmdToday } from "../../../lib/format/dateFormat";
import {
  legacyUserValue,
  tryDecodeLegacyUser,
} from "../../../lib/legacySelectValue";
import { formatLineUnitPriceDisplay } from "../../../lib/format/priceInput";
import {
  requesterDepartmentPathForEmployeeNo,
  type EmployeeDirectoryItem,
  type UserItem,
} from "../../../api/user";
import type { OrganizationUnitNode } from "../../../api/organization";
import type { PurchaseOrderDetail } from "../../../api/purchaseOrder";
import {
  representativeProductLabel,
  type RepresentativeProduct,
} from "../../../api/products";
import type { AuthUser } from "../../../types/authUser";
import type { ItemRow } from "../types";

type UseOrderFormHeaderStateParams = {
  isNew: boolean;
  order: PurchaseOrderDetail | undefined;
  items: ItemRow[];
  employeeDirectory: EmployeeDirectoryItem[];
  usersForRequester: UserItem[];
  organizationTree: OrganizationUnitNode[];
  productList: RepresentativeProduct[];
  purchaseOrderTypeCodes: { code: string; name?: string }[];
  purchaseOrderStatusCodes: { code: string; name?: string }[];
  user: AuthUser | null | undefined;
};

export function useOrderFormHeaderState({
  isNew,
  order,
  items,
  employeeDirectory,
  usersForRequester,
  organizationTree,
  productList,
  purchaseOrderTypeCodes,
  purchaseOrderStatusCodes,
  user,
}: UseOrderFormHeaderStateParams) {
  const [title, setTitle] = useState("");
  const [isTitleAutoFilled, setIsTitleAutoFilled] = useState(true);
  const [partnerId, setPartnerId] = useState<string>("");
  const [orderDate, setOrderDate] = useState(localYmdToday());
  const [dueDate, setDueDate] = useState("");
  const [requestDeliveryDate, setRequestDeliveryDate] = useState("");
  const [requesterUserSelectValue, setRequesterUserSelectValue] = useState("");
  const [vendorOrderNo, setVendorOrderNo] = useState("");
  const [vendorRequest, setVendorRequest] = useState("");
  const [specialNote, setSpecialNote] = useState("");
  const [orderTypeCode, setOrderTypeCode] = useState("");
  const [orderStatusCode, setOrderStatusCode] = useState("");
  const [orderCurrencyCode, setOrderCurrencyCode] = useState("KRW");
  const [exchangeRateCurrencyCode, setExchangeRateCurrencyCode] =
    useState("KRW");
  const [exchangeRateInput, setExchangeRateInput] = useState("");
  const [pendingFilesForCreate, setPendingFilesForCreate] = useState<File[]>([]);
  const [uploadingExistingFileNames, setUploadingExistingFileNames] = useState<
    string[]
  >([]);
  const [recentlyUploadedFileNames, setRecentlyUploadedFileNames] = useState<
    string[]
  >([]);
  const [fileDeleteConfirmId, setFileDeleteConfirmId] = useState<number | null>(null);

  const recentlyUploadedFileTimersRef = useRef<
    Record<string, ReturnType<typeof setTimeout>>
  >({});

  const firstLineTitleParts = useMemo(() => {
    const firstRow = items[0];
    const qty = firstRow && Number.isFinite(firstRow.qty) ? firstRow.qty : 0;
    if (!firstRow || !firstRow.productId.trim()) {
      return { businessLabel: "제품미선택", productName: "", qty };
    }
    const product = productList.find((p) => p.id === firstRow.productId);
    if (!product) {
      return { businessLabel: "제품미선택", productName: "", qty };
    }
    const businessName = (product.businessName ?? "").trim();
    const businessCode = (product.businessCode ?? "").trim();
    const productName = (product.productName ?? "").trim();
    const businessLabel =
      businessName ||
      businessCode ||
      representativeProductLabel(product).replace(/\s+/g, "");
    return { businessLabel, productName, qty };
  }, [items, productList]);

  const autoGeneratedTitle = useMemo(() => {
    const compactDate =
      compactYmd(orderDate || localYmdToday()) ||
      compactYmd(localYmdToday()) ||
      "";
    const { businessLabel, productName, qty } = firstLineTitleParts;
    let productSegment = businessLabel;
    if (
      productName &&
      productName !== businessLabel &&
      !businessLabel.includes(`(${productName})`)
    ) {
      productSegment = `${businessLabel} (${productName})`;
    }
    const dateAndProduct = compactDate
      ? `${compactDate}-${productSegment}`
      : productSegment;
    return `${dateAndProduct} - ${qty}`;
  }, [orderDate, firstLineTitleParts]);

  const requesterDepartmentForPayload = useMemo(() => {
    const fromEmployee = requesterDepartmentPathForEmployeeNo(
      requesterUserSelectValue,
      usersForRequester,
      organizationTree
    );
    if (fromEmployee) return fromEmployee;
    if (!isNew && order) {
      return (
        order.requesterDepartment?.trim() ||
        order.requestDepartment?.trim() ||
        ""
      );
    }
    return "";
  }, [
    requesterUserSelectValue,
    usersForRequester,
    organizationTree,
    isNew,
    order,
  ]);

  const defaultOrderTypeCode = useMemo(() => {
    if (purchaseOrderTypeCodes.length === 0) return "";
    const general = purchaseOrderTypeCodes.find((c) => c.code === "GENERAL");
    return (general ?? purchaseOrderTypeCodes[0])?.code ?? "";
  }, [purchaseOrderTypeCodes]);

  const defaultOrderStatusCode = useMemo(() => {
    if (purchaseOrderStatusCodes.length === 0) return "";
    const registered = purchaseOrderStatusCodes.find(
      (c) => c.code === "PO_REGISTERED"
    );
    return (registered ?? purchaseOrderStatusCodes[0])?.code ?? "";
  }, [purchaseOrderStatusCodes]);

  const effectiveOrderTypeCode = isNew
    ? orderTypeCode || defaultOrderTypeCode
    : orderTypeCode;

  const effectiveOrderStatusCode = isNew
    ? orderStatusCode || defaultOrderStatusCode
    : orderStatusCode;

  const requesterUserOptions = useMemo(() => {
    const opts = employeeDirectory.map((u) => ({
      value: String(u.employeeNo),
      label: `${u.name} (${u.employeeNo})`,
    }));
    const sel = requesterUserSelectValue;
    if (!sel || opts.some((o) => o.value === sel)) return opts;
    const legacyName = tryDecodeLegacyUser(sel);
    if (legacyName) {
      opts.unshift({ value: sel, label: `${legacyName} (저장된 값)` });
      return opts;
    }
    opts.unshift({ value: sel, label: `사용자 #${sel}` });
    return opts;
  }, [employeeDirectory, requesterUserSelectValue]);

  useEffect(() => {
    if (!isNew && order) {
      queueMicrotask(() => setIsTitleAutoFilled(false));
      startTransition(() => {
        setTitle(order.title ?? "");
        setPartnerId(String(order.partnerId ?? ""));
        setOrderDate(order.orderDate ?? localYmdToday());
        setDueDate(order.dueDate ?? "");
        const persistedCurrencyCode = normalizeCurrencyCode(order.currencyCode);
        setOrderCurrencyCode(persistedCurrencyCode);
        setExchangeRateCurrencyCode(persistedCurrencyCode);
        setRequestDeliveryDate(order.requestDeliveryDate ?? "");
        setVendorOrderNo(order.vendorOrderNo ?? "");
        setVendorRequest(order.vendorRequest ?? "");
        setSpecialNote(order.specialNote ?? "");
        setOrderTypeCode((order.orderType ?? "").trim());
        setOrderStatusCode(
          String(order.status ?? order.orderStatus ?? "").trim()
        );
        const persistedExchangeRate = Number(order.exchangeRate ?? NaN);
        setExchangeRateInput(
          Number.isFinite(persistedExchangeRate)
            ? formatLineUnitPriceDisplay(persistedExchangeRate)
            : ""
        );
      });
    }
  }, [isNew, order]);

  useEffect(() => {
    if (!isNew) return;
    if (!isTitleAutoFilled) return;
    queueMicrotask(() => setTitle(autoGeneratedTitle));
  }, [isNew, isTitleAutoFilled, autoGeneratedTitle]);

  useEffect(() => {
    if (isNew || !order) return;
    const name = (order.requesterName ?? "").trim();
    if (!name) {
      queueMicrotask(() => setRequesterUserSelectValue(""));
      return;
    }
    if (employeeDirectory.length === 0) return;
    const u = employeeDirectory.find((x) => x.name === name);
    if (u) queueMicrotask(() => setRequesterUserSelectValue(String(u.employeeNo)));
    else queueMicrotask(() => setRequesterUserSelectValue(legacyUserValue(name)));
  }, [isNew, order, employeeDirectory]);

  useEffect(() => {
    if (!isNew) return;
    if (requesterUserSelectValue !== "") return;
    if (user?.employeeNo == null || employeeDirectory.length === 0) return;
    const me = employeeDirectory.find((u) => u.employeeNo === user.employeeNo);
    if (me) {
      queueMicrotask(() => setRequesterUserSelectValue(String(me.employeeNo)));
    }
  }, [isNew, requesterUserSelectValue, employeeDirectory, user?.employeeNo]);

  const markFileUploadCompleted = useCallback((fileName: string) => {
    if (!fileName) return;
    setRecentlyUploadedFileNames((prev) =>
      prev.includes(fileName) ? prev : [...prev, fileName]
    );
    const existingTimer = recentlyUploadedFileTimersRef.current[fileName];
    if (existingTimer) clearTimeout(existingTimer);
    recentlyUploadedFileTimersRef.current[fileName] = setTimeout(() => {
      setRecentlyUploadedFileNames((prev) =>
        prev.filter((name) => name !== fileName)
      );
      delete recentlyUploadedFileTimersRef.current[fileName];
    }, 3500);
  }, []);

  const initialHeaderSnapshot = useMemo(() => {
    if (isNew) {
      return {
        title: "",
        partnerId: "",
        orderDate: localYmdToday(),
        dueDate: "",
        requestDeliveryDate: "",
        requesterUserSelectValue: "",
        vendorOrderNo: "",
        vendorRequest: "",
        specialNote: "",
        orderTypeCode: "",
        orderStatusCode: "",
        orderCurrencyCode: "KRW",
        exchangeRateCurrencyCode: "KRW",
        exchangeRateInput: "",
        pendingFileCount: 0,
      };
    }
    if (!order) return null;
    const persistedCurrencyCode = normalizeCurrencyCode(order.currencyCode);
    const persistedExchangeRate = Number(order.exchangeRate ?? NaN);
    const requesterName = (order.requesterName ?? "").trim();
    let requesterSelect = "";
    if (requesterName && employeeDirectory.length > 0) {
      const u = employeeDirectory.find((x) => x.name === requesterName);
      requesterSelect = u
        ? String(u.employeeNo)
        : legacyUserValue(requesterName);
    }
    return {
      title: order.title ?? "",
      partnerId: String(order.partnerId ?? ""),
      orderDate: order.orderDate ?? localYmdToday(),
      dueDate: order.dueDate ?? "",
      requestDeliveryDate: order.requestDeliveryDate ?? "",
      requesterUserSelectValue: requesterSelect,
      vendorOrderNo: order.vendorOrderNo ?? "",
      vendorRequest: order.vendorRequest ?? "",
      specialNote: order.specialNote ?? "",
      orderTypeCode: (order.orderType ?? "").trim(),
      orderStatusCode: String(order.status ?? order.orderStatus ?? "").trim(),
      orderCurrencyCode: persistedCurrencyCode,
      exchangeRateCurrencyCode: persistedCurrencyCode,
      exchangeRateInput: Number.isFinite(persistedExchangeRate)
        ? formatLineUnitPriceDisplay(persistedExchangeRate)
        : "",
      pendingFileCount: 0,
    };
  }, [isNew, order, employeeDirectory]);

  const isHeaderDirty = useMemo(() => {
    if (!initialHeaderSnapshot) return false;
    const titleDirty = isNew
      ? !isTitleAutoFilled
      : title !== initialHeaderSnapshot.title;
    return (
      titleDirty ||
      partnerId !== initialHeaderSnapshot.partnerId ||
      orderDate !== initialHeaderSnapshot.orderDate ||
      dueDate !== initialHeaderSnapshot.dueDate ||
      requestDeliveryDate !== initialHeaderSnapshot.requestDeliveryDate ||
      requesterUserSelectValue !==
        initialHeaderSnapshot.requesterUserSelectValue ||
      vendorOrderNo !== initialHeaderSnapshot.vendorOrderNo ||
      vendorRequest !== initialHeaderSnapshot.vendorRequest ||
      specialNote !== initialHeaderSnapshot.specialNote ||
      orderTypeCode !== initialHeaderSnapshot.orderTypeCode ||
      orderStatusCode !== initialHeaderSnapshot.orderStatusCode ||
      orderCurrencyCode !== initialHeaderSnapshot.orderCurrencyCode ||
      exchangeRateCurrencyCode !== initialHeaderSnapshot.exchangeRateCurrencyCode ||
      exchangeRateInput !== initialHeaderSnapshot.exchangeRateInput ||
      (isNew && pendingFilesForCreate.length > initialHeaderSnapshot.pendingFileCount)
    );
  }, [
    initialHeaderSnapshot,
    isNew,
    isTitleAutoFilled,
    title,
    partnerId,
    orderDate,
    dueDate,
    requestDeliveryDate,
    requesterUserSelectValue,
    vendorOrderNo,
    vendorRequest,
    specialNote,
    orderTypeCode,
    orderStatusCode,
    orderCurrencyCode,
    exchangeRateCurrencyCode,
    exchangeRateInput,
    pendingFilesForCreate.length,
  ]);

  const addPendingFileForCreate = (files: File[]) => {
    if (files.length === 0) return;
    setPendingFilesForCreate((prev) => [...prev, ...files].slice(0, 20));
    notify.success(`첨부 대기 목록에 ${files.length}건 추가되었습니다.`);
  };

  const removePendingFileForCreate = (targetIndex: number) => {
    setPendingFilesForCreate((prev) =>
      prev.filter((_, index) => index !== targetIndex)
    );
  };

  return {
    title,
    setTitle,
    isTitleAutoFilled,
    setIsTitleAutoFilled,
    partnerId,
    setPartnerId,
    orderDate,
    setOrderDate,
    dueDate,
    setDueDate,
    requestDeliveryDate,
    setRequestDeliveryDate,
    requesterUserSelectValue,
    setRequesterUserSelectValue,
    vendorOrderNo,
    setVendorOrderNo,
    vendorRequest,
    setVendorRequest,
    specialNote,
    setSpecialNote,
    orderTypeCode,
    setOrderTypeCode,
    orderStatusCode,
    setOrderStatusCode,
    orderCurrencyCode,
    setOrderCurrencyCode,
    exchangeRateCurrencyCode,
    setExchangeRateCurrencyCode,
    exchangeRateInput,
    setExchangeRateInput,
    pendingFilesForCreate,
    setPendingFilesForCreate,
    uploadingExistingFileNames,
    setUploadingExistingFileNames,
    recentlyUploadedFileNames,
    fileDeleteConfirmId,
    setFileDeleteConfirmId,
    requesterDepartmentForPayload,
    effectiveOrderTypeCode,
    effectiveOrderStatusCode,
    requesterUserOptions,
    isHeaderDirty,
    markFileUploadCompleted,
    addPendingFileForCreate,
    removePendingFileForCreate,
  };
}
